name: Docker Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Construir imagen
        run: docker build -t devm0n/lasallefoods_api:latest .

      - name: Publicar en Docker Hub
        run: docker push devm0n/lasallefoods_api:latest

      - name: Ejecutar migracion en produccion
        run: |
          docker container run --rm \
          -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
          -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
          -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
          -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
          devm0n/lasallefoods_api:latest migrate --yes
