name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Construir imagen
        run: docker build -t devm0n/lasallefoods_api:latest .

      - name: Publicar en Docker Hub
        run: docker push devm0n/lasallefoods_api:latest
